# Site settings
title: Doing the Thing
email: l4.bailey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   The writer, not the model or the voice actor.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laurabailey.com.au" # the base hostname & protocol for your site
twitter_username: produdfctititty
github_username:  laubai

# Build settings
markdown: kramdown
